global:
  scrape_interval: 60s
remote_write:
  - url: https://prometheus-prod-39-prod-eu-north-0.grafana.net/api/prom/push
    basic_auth:
      username: <user> 
      password: <pass>
scrape_configs:
  - job_name: node
    static_configs:
        - targets:
            - "localhost:9090"
          labels:
              env: "pi"
  - job_name: dht
    static_configs:
        - targets:
            - "localhost:8000"
          labels:
              env: "pi"
